# название
name: Project test & build

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      # Установка зависимостей
      - name: Install 🔧
        run: npm install
      #Основная сборка без СВГ
      - name: Build 👷
        run: npm run build
      #Сборка СВГ спрайта
      - name: SVG
        run: npm run createSvgSprite
      #Пуш собранного проекта в ветку gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.Deploy }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
